### ISSUE TITLE
Mark as a pull request for a corresponding issue

### ISSUE THREAD

**Issue by twolfson** [nodebugme/discussion#4]
I triaged https://github.com/joyent/node/pull/8602 under the pretense of all the answers being about https://github.com/joyent/node/issues/7676. Should we make a way to link PR's to issues to prevent double triaging?

**Comment by mcwhittemore** [comment]
Just tried to triage [joyent/node#8212](https://github.com/joyent/node/pull/8212) but most of the questions are very bug/request orientated and 8212 is a PR to solve [joyent/node#8210](https://github.com/joyent/node/issues/8210). Should PRs be removed fully? Maybe they get a different question flow?

**Comment by twolfson** [comment]
I think they should be left in but need an away to combine them. Sometimes people open PRs without opening an issue first. I don't think marking it as a duplicate applies since usually you close the duplicate and with a PR, they depend on one another.

**Comment by mcwhittemore** [comment]
Yea. I think if its a PR the first question should be "does this relate to another issue" and if it does it should ask questions about if it is a good answer otherwise it should be treated like an issue.

**Comment by srl295** [comment]
> I triaged joyent/node#8602 under the pretense of all the answers being about joyent/node#7676. Should we make a way to link PR's to issues to prevent double triaging?

What does this mean?

**Comment by twolfson** [comment]
I am guessing you seeing a link from `#8602/#7676` and are confused what this repo is about. I will try to clarify with background on `nodebugme`. `nodebugme` is a project/site attempting to triage all open issues on `joyent/node`.

https://nodebug.me/

I was assigned to triage `#8602`, which is a PR, and noticed that it is resolving to `#7676`. I decided to answer the questions for `#8602` as if they were for `#7676` because `#8602` was lacking of a thread. I decided to open this issue to determine how we should handle the situation in the future.

**Comment by srl295** [comment]
@twolfson yeah.. where does the triaging go? 
Anyways- https://github.com/joyent/node/pull/8602 fixes https://github.com/joyent/node/issues/8521 which was introduced by the already-pulled https://github.com/joyent/node/pull/7719.  https://github.com/joyent/node/issues/7676 is the "big picture" which depends on https://github.com/joyent/node/pull/7719 being done, but has some more work.  There's also https://github.com/joyent/node/pull/8681 which fixes another issue with https://github.com/joyent/node/issues/7676  .. does that help?

**Comment by twolfson** [comment]
I don't know the mechanism where triage results are added to the issues themselves. Maybe open another issue in this repo to get that clarified?

Regarding the issues themselves, yes it helps this discussion. Issues are a tangled web of dependencies o_o

**Comment by srl295** [comment]
@twolfson https://nodebug.me/ says a core contributor looks at it and something about sarcasm tags.

Anyways, I think the original approach makes some sense. https://github.com/joyent/node/pull/8602 just supports https://github.com/joyent/node/issues/7676

**Comment by chrisdickinson** [comment]
@srl295 sorry about that! I'm the core contributor in question, and I've been working on exposing the results through a REST API for the rest of the contributors / the general public.

I'm pretty convinced that we should remove PRs from the triage queue. They necessitate a totally different set of questions. Somewhat embarrassingly, I was unaware they were showing up in the queue!

**Comment by twolfson** [comment]
Works for me. I guess we will leave the issue open until that is implemented in `nodebugme/site`.

**Comment by chrisdickinson** [comment]
It should be fixed now.

**Comment by twolfson** [comment]
Yay =3
